GitHub:
- changed-files:
  - any-glob-to-any-file:
    - .github/**

BeMatch:
- changed-files:
  - any-glob-to-any-file:
    - App/BeMatch/**
    - Packages/BeMatch/**
    - BeMatch.xcworkspace/**

FlyCam:
- changed-files:
  - any-glob-to-any-file:
    - App/FlyCam/**
    - Packages/FlyCam/**
    - FlyCam.xcworkspace/**

MatchCore:
- changed-files:
  - any-glob-to-any-file:
    - Packages/MatchCore/**
    - MatchCore.xcworkspace/**

Dependencies:
- changed-files:
  - any-glob-to-any-file:
    - Packages/Dependencies/**
    - Dependencies.xcworkspace/**
