name: build ios
description: 'Build ios'
inputs:
  platform_ios:
    description: 'iOS platform'
    required: true
  workspace:
    description: 'Workspace'
    required: true
  key:
    description: 'Cache key'
    required: true

runs:
  using: composite
  steps:
    - uses: irgaly/xcode-cache@v1
      with:
        key: ${{ inputs.key }}-xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
        restore-keys: ${{ inputs.key }}-xcode-cache-deriveddata-${{ github.workflow }}-

    - run: make bootstrap
      shell: bash

    - run: xcodebuild build -workspace "${{ inputs.workspace }}" -scheme "App (Staging project)" -skipMacroValidation -destination platform="${{ inputs.platform_ios }}" | xcpretty
      shell: bash
