name: FlyCam

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - App/FlyCam/**/*
      - Packages/FlyCam/**/*
      - Packages/SDK/**/*
      - .github/workflows/flycam.yml
      - Makefile
  pull_request:
    paths:
      - App/FlyCam/**/*
      - Packages/FlyCam/**/*
      - Packages/SDK/**/*
      - .github/workflows/flycam.yml
      - Makefile

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 15 Pro,OS=17.0.1
  FLYCAM_FILE_FIREBASE_STAGING: ${{ secrets.FLYCAM_FILE_FIREBASE_STAGING }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/xcode-cache@v1
        with:
          key: flycam-xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: flycam-xcode-cache-deriveddata-${{ github.workflow }}-
      - run: make bootstrap
      - run: xcodebuild build -workspace FlyCam.xcworkspace -scheme "App (Staging project)" -skipMacroValidation -destination platform="${{ env.PLATFORM_IOS }}" | xcpretty
