name: MatchCore

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Packages/MatchCore/**/*
      - .github/workflows/matchcore.yml
  pull_request:
    paths:
      - Packages/MatchCore/**/*
      - .github/workflows/matchcore.yml

env:
  PLATFORM_IOS: iOS Simulator,name=iPhone 15 Pro,OS=17.0.1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/xcode-cache@v1
        with:
          key: matchcore-xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
          restore-keys: matchcore-xcode-cache-deriveddata-${{ github.workflow }}-
      - run: xcodebuild build -workspace MatchCore.xcworkspace -scheme "AppLogic" -skipMacroValidation -sdk iphonesimulator | xcpretty
