name: playground

on:
  workflow_dispatch:

jobs:
  version-up:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CURRENT_VERSION=$(defaults read $(pwd)/App/BeMatch/Multiplatform/Staging/Info CFBundleShortVersionString)" >> $GITHUB_OUTPUT
        id: current-version
      - run: |
          CURRENT_VERSION=${{ steps.current-version.outputs.CURRENT_VERSION }}
          echo "NEXT_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{print $1,$2+1,0}')" >> $GITHUB_OUTPUT
        id: next-version
      - run: |
          echo "${{ steps.next-version.outputs.NEXT_VERSION }}"
